### ISSUE TITLE
Mux shape is a rectangle when exported as PDF

### ISSUE THREAD

**Issue by patrickrst** [nopeslide/drawio_rtl_plugin#22]
Same for DeMux and Crossbar. This does not happen when exporting to PNG or SVG.

Not sure if it's related to a property that can be changed or if it's a bug with drawio.

Using release 0.0.7 of drawio_rtl_plugin

drawio version: diagrams.net 14.5.1
OS: Linux, package from flathub.org

**Comment by nopeslide** [comment]
this is a drawio bug. the drawio pdf exporter does not load plugins.
see i.e. https://github.com/jgraph/drawio/pull/1257
